openapi: 3.0.3
info:
  title: Tetris Web Highscore API
  version: 0.1.0
servers:
  - url: https://api.example.com
paths:
  /scores:
    get:
      summary: List top scores
      parameters:
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 10 }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Score"
    post:
      summary: Submit a score
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScoreInput"
      responses:
        "201": { description: Created }
        "400": { description: Bad Request }
components:
  schemas:
    Score:
      type: object
      required: [id, nickname, points, createdAt, client]
      properties:
        id: { type: string }
        nickname: { type: string, minLength: 1, maxLength: 16 }
        points: { type: integer, minimum: 0 }
        createdAt: { type: string, format: date-time }
        client:
          type: object
          properties:
            version: { type: string }
            ua: { type: string, maxLength: 128 }
    ScoreInput:
      type: object
      required: [nickname, points]
      properties:
        nickname: { type: string, minLength: 1, maxLength: 16 }
        points: { type: integer, minimum: 0 }
        client:
          type: object
          properties:
            version: { type: string }
            ua: { type: string, maxLength: 128 }
